### ISSUE TITLE
Can't compile on Ubuntu 21.10

### ISSUE THREAD

**Issue by cybik** [illnyang/nvlax#1]
Even having installed liblief-dev, it refuses to compile properly:

```gitstore/nvlax/src/lax_encode.cc: In function ‘int main(int, char**)’:
gitstore/nvlax/src/lax_encode.cc:45:78: error: ‘class LIEF::Symbol’ has no member named ‘value’
   45 |         auto v_func_bytes = bin->get_content_from_virtual_address(f_nvenc_ci.value(), 0x260);
      |                                                                              ^~~~~
gitstore/nvlax/src/lax_encode.cc:53:37: error: ‘class LIEF::Symbol’ has no member named ‘value’
   53 |                 offset = f_nvenc_ci.value() +
      |```

**Comment by cybik** [comment]
Looks like the pulling in of LIEF somehow explodes.

**Comment by illnyang** [comment]
You can uninstall the `liblief-dev` package; all dependencies in this project are compiled independently of your system package management system and are statically linked.

As for the issue itself, it seems that CMake picked up my system-wide installation of LIEF instead of using the locally fetched one. I'm looking into this right now.

**Comment by illnyang** [comment]
Should be fixed with https://github.com/illnyang/nvlax/commit/6eb4c49597a68e5df3fefb5f09a74e71f0814b17
Let me know if it works now :)

**Comment by cybik** [comment]
Yeah *now* it's compiling properly. I'll be testing in a bit.

**Comment by cybik** [comment]
Compiled, patched libs, and the nvfbc patched lib works with OBS. Nice!
